# Salin isi ~/.config/btop/btop.conf kamu ke sini
# Contoh:
# color_theme = "Default"
# theme_background = True
# truecolor = True
# force_tty = False
# graph_symbol = "braille"
# update_ms = 2000
# cpu_graph_upper = "total"
# cpu_graph_lower = "user"
# mem_graphs = True
# show_disks = True
